# Generated by Django 5.2.5 on 2025-09-12 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tareas", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tarea",
            old_name="updated_at",
            new_name="datecomplete",
        ),
    ]
